title: Tom Ray - Musician & Creator
description: A blog about music, creativity, and the journey of being a musician
author: Tom Ray
email: your-email@example.com
url: "https://tomray.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 9
paginate_path: "/posts/:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tom Ray"
      category: "General"
      tags: []

# Social Media Platforms
# Add or remove platforms by editing this array
# Each platform needs: name, url, icon_class
social_platforms:
  - name: "Mastodon"
    url: "https://mastodon.social/@tmray"
    icon_class: "icon-mastodon"
  - name: "Instagram"
    url: "https://instagram.com/tmray"
    icon_class: "icon-instagram"
  - name: "Pixelfed"
    url: "https://pixelfed.social/@tmray"
    icon_class: "icon-pixelfed"
  - name: "Facebook"
    url: "https://facebook.com/tomrayswebsite"
    icon_class: "icon-facebook"
  - name: "YouTube"
    url: "https://youtube.com/@tomrayrules"
    icon_class: "icon-youtube"
  # - name: "Twitter"
  #   url: "https://twitter.com/yourusername"
  #   icon_class: "icon-twitter"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
